name: deploy order order-backend

on: 
  push: 
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout github
      uses: actions/checkout@v2
    - name: install kubectl
      uses: azure/setup-kubectl@v3
      with: 
        version: "v1.25.9"
      id: install
    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ap-northeast-2

    # apigateway
    - name: update cluster infomation
      run: aws eks update-kubeconfig --name 6team-cluster --region ap-northeast-2

    - name: Login to ECR
      id: login-ecr-apigateway
      uses: aws-actions/amazon-ecr-login@v1

    - name: build and push docker image to ecr
      env: 
        REGISTRY: XXX.dkr.ecr.ap-northeast-2.amazonaws.com
        REPOSITORY: chaserchoi/apigateway
        IMAGE_TAG: latest
      run: |
        docker build \ 
        -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \ 
        -f ./apigateway/Dockerfile ./apigateway 
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: eks kubectl apply
      run: | 
        kubectl rollout restart deployment apigateway-depl -n chaserchoi

    # ordering
    - name: Login to ECR
      id: login-ecr-ordering
      uses: aws-actions/amazon-ecr-login@v1

    - name: build and push docker image to ecr
      env:
        REGISTRY: XXX.dkr.ecr.ap-northeast-2.amazonaws.com
        REPOSITORY: chaserchoi/ordering
        IMAGE_TAG: latest
      run: |
        docker build \
        -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
        -f ./ordering/Dockerfile ./ordering
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: eks kubectl apply
      run: |
        kubectl rollout restart deployment ordering-depl -n chaserchoi

    # product
    - name: Login to ECR
      id: login-ecr-product
      uses: aws-actions/amazon-ecr-login@v1

    - name: build and push docker image to ecr
      env:
        REGISTRY: XXX.dkr.ecr.ap-northeast-2.amazonaws.com
        REPOSITORY: chaserchoi/product
        IMAGE_TAG: latest
      run: |
        docker build \
        -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
        -f ./product/Dockerfile ./product
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: eks kubectl apply
      run: |
        kubectl rollout restart deployment product-depl -n chaserchoi

    # member
    - name: Login to ECR
      id: login-ecr-member
      uses: aws-actions/amazon-ecr-login@v1

    - name: build and push docker image to ecr
      env:
        REGISTRY: XXX.dkr.ecr.ap-northeast-2.amazonaws.com
        REPOSITORY: chaserchoi/member
        IMAGE_TAG: latest
      run: |
        docker build \
        -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
        -f ./member/Dockerfile ./member
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: eks kubectl apply
      run: |
        kubectl rollout restart deployment member-depl -n chaserchoi
